services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:3000
    restart: unless-stopped
    command: ["npm", "run", "start:server"]
    environment:
      APP_PORT: 3000
      COOKIE_SECRET: ${COOKIE_SECRET}
      FULL_VENDURE_HOST: ${FULL_VENDURE_HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}
      #EMAIL CONFIG
      SENDGRID_USERNAME: ${SENDGRID_USERNAME}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      STELLATE_PURGE_API_TOKEN: ${STELLATE_PURGE_API_TOKEN}
      ASSETS_URL_PREFIX: ${ASSETS_URL_PREFIX}
    # depends_on:
    #   - ldb
    volumes:
      - ./static:/usr/src/app/static
  worker:
    image: 0zyxel0/sc-superapp-store:latest
    command: ["npm", "run", "start:worker"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

